version: 0.1.6.{build}

image:
  - Visual Studio 2017

# git clone recursively. Fix taken from Sergey S. Betke's answer to
# https://github.com/appveyor/ci/issues/899
clone_script:
  - cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

cache:
  - C:\Users\appveyor\AppData\Local\NuGet\Cache

install:
  - set VERNUM=0.1.6
  - echo %APPVEYOR_REPO_TAG%
  # Build packages as VERNUM-ci{build}
  - ps: if ($env:APPVEYOR_REPO_TAG -eq $True) { $env:PKG_VERSION = $env:VERNUM; } else { $env:PKG_VERSION = "$($env:VERNUM)-ci$($env:APPVEYOR_BUILD_NUMBER)"; }

  # Grab a compiled version of compare-test and add it to the PATH variable.
  - curl -L https://github.com/jonathanvdc/compare-test/releases/download/v0.1.5/compare-test.zip > compare-test.zip
  - mkdir compare-test
  - 7z x compare-test.zip -ocompare-test
  - set PATH=%PATH%;%cd%\compare-test
  # Add cygwin binaries to the PATH
  - set PATH=%PATH%;C:\cygwin\bin

build_script:
  # Restore NuGet packages.
  - nuget restore cs-wasm.sln
  # Build cs-wasm.
  - msbuild /p:Configuration=Debug /verbosity:quiet /nologo cs-wasm.sln
  - msbuild /p:Configuration=Release /verbosity:quiet /nologo cs-wasm.sln

after_build:
  # Create a folder that contains all tools and zip it.
  - mkdir cs-wasm-tools
  - xcopy wasm-cat\bin\Release\net47\wasm-cat.exe cs-wasm-tools
  - xcopy wasm-dump\bin\Release\net47\wasm-dump.exe cs-wasm-tools
  - xcopy wasm-interp\bin\Release\net47\wasm-interp.exe cs-wasm-tools
  - xcopy wasm-opt\bin\Release\net47\wasm-opt.exe cs-wasm-tools
  - 7z a cs-wasm-tools.zip %APPVEYOR_BUILD_FOLDER%\cs-wasm-tools\*
  # Create the NuGet package
  - nuget pack -Version %PKG_VERSION% libwasm.nuspec

test_script:
  # Run the tests
  - compare-test run-tests.test

artifacts:
  - path: cs-wasm-tools.zip
    name: cs-wasm-tools
  - path: '*.nupkg'
    name: nupkgs

deploy:
  - provider: NuGet
    server:
    api_key:
      secure: vIYC0UO8DFL2HXrIu20ZQs1NR31SvGZWioDBgXzyMwJEd5dySh5peABsrwWvKzU1
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      branch: master # Release from master branch only.
      appveyor_repo_tag: true # Deploy on tag push only.
  - provider: GitHub
    release: cs-wasm v$(VERNUM)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release description' # Fill this out later.
    auth_token:
      secure: 693ZX2DdyyjDOqpJaJlUMO1hcMtLbsqMnCLzQVUEq7JjGb+bfEbaB/oMO0b26KZo
    artifact: cs-wasm-tools.zip # Release the cs-wasm tools as an artifact.
    draft: true  # Make this a draft.
    prerelease: false
    on:
      branch: master # Release from master branch only.
      appveyor_repo_tag: true # Deploy on tag push only.
