version: 0.1.7.{build}

image:
  - Visual Studio 2019

cache:
  - C:\Users\appveyor\AppData\Local\NuGet\Cache

install:
  # Clone submodules.
  - git submodule update --init --recursive

    # Generate a NuGet package version number.
  - echo %APPVEYOR_REPO_TAG%
  - C:\Python34\python.exe Tools\CI\version-number.py %APPVEYOR_BUILD_VERSION% > pkg-version.txt
  - set /p PKG_VERSION=<pkg-version.txt
  - echo %PKG_VERSION%

  # Grab a compiled version of compare-test and add it to the PATH variable.
  - curl -L https://github.com/jonathanvdc/compare-test/releases/download/v0.1.5/compare-test.zip > compare-test.zip
  - mkdir compare-test
  - 7z x compare-test.zip -ocompare-test
  - set PATH=%PATH%;%cd%\compare-test
  # Add cygwin binaries to the PATH
  - set PATH=%PATH%;C:\cygwin\bin

build_script:
  # Restore NuGet packages.
  - nuget restore cs-wasm.sln
  # Build cs-wasm.
  - msbuild /p:Configuration=Debug /verbosity:quiet /nologo cs-wasm.sln
  - msbuild /p:Configuration=Release /verbosity:quiet /nologo cs-wasm.sln

after_build:
  # Create a folder that contains all tools and zip it.
  - mkdir cs-wasm-tools
  - xcopy wasm-cat\bin\Release\net47\wasm-cat.exe cs-wasm-tools
  - xcopy wasm-dump\bin\Release\net47\wasm-dump.exe cs-wasm-tools
  - xcopy wasm-interp\bin\Release\net47\wasm-interp.exe cs-wasm-tools
  - xcopy wasm-opt\bin\Release\net47\wasm-opt.exe cs-wasm-tools
  - 7z a cs-wasm-tools.zip %APPVEYOR_BUILD_FOLDER%\cs-wasm-tools\*
  # Create the NuGet packages
  - nuget pack -Version %PKG_VERSION% libwasm.nuspec
  - nuget pack -Version %PKG_VERSION% libwasm-text.nuspec

test_script:
  # Run the tests
  - unit-tests\bin\Debug\net47\unit-tests.exe 1234
  - compare-test run-tests.test

artifacts:
  - path: cs-wasm-tools.zip
    name: cs-wasm-tools
  - path: '*.nupkg'
    name: nupkgs

deploy:
  - provider: NuGet
    server:
    api_key:
      secure: gMPbXqsgejstJ7SgTV98Fx2oG9U75tlT43eto2K9RpnCT7swtOl1JhBmujG29E2l
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true # Deploy on tag push only.
  - provider: GitHub
    release: cs-wasm v$(VERNUM)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release description' # Fill this out later.
    auth_token:
      secure: uD30BxiIToiU/QF5vqzg07XGow2lyfagXLn1eWGi6228/+OpD1za2z/Z7tB2j4+8
    artifact: cs-wasm-tools.zip # Release the cs-wasm tools as an artifact.
    draft: true  # Make this a draft.
    prerelease: false
    on:
      branch: master # Release from master branch only.
      appveyor_repo_tag: true # Deploy on tag push only.
